import "../styles/globals.css";
import Nav from "../components/Nav";
import Footer from "../components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-5">
        <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
